<?php

/**
 * @file
 * Hook implementations for Social Auth Dribbble module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_auth_dribbble_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    case 'social_auth_dribbble.settings_form':
      $output = '<h3>' . t('Configuration instructions') . '</h3>';
      $output .= '<p>';
      $output .= t('Configuration instructions and other useful documentation can be found from <a href="@handbook-url">Social Auth Dribbble Handbook</a>.', ['@handbook-url' => 'https://www.drupal.org/docs/8/modules/social-api/social-api-2x/social-auth-2x/social-auth-dribbble-2x-installation']);
      $output .= '</p>';
      break;

  }

  return $output;
}
